# Generated by Django 5.1.7 on 2025-03-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_first_name_contact_last_name_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='initial',
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
    ]
