# Generated by Django 5.1.7 on 2025-03-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('to_do', 'To do'), ('in_progress', 'In progress'), ('await_feedback', 'Await feedback'), ('done', 'Done')], default='to_do', max_length=50),
        ),
    ]
