# Generated by Django 5.1.7 on 2025-03-20 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_color'),
        ('tasks', '0009_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedto',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='contacts.contact'),
        ),
    ]
