# Generated by Django 5.1.7 on 2025-03-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_assignedto_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedto',
            old_name='profile',
            new_name='contact',
        ),
    ]
