# Generated by Django 5.1.7 on 2025-03-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_rename_profile_assignedto_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Technical Task', 'Technical Task'), ('User Story', 'User Story')], default='user_story', max_length=20),
        ),
    ]
