# Generated by Django 5.1.7 on 2025-03-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_task_prio'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='done',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
